using System;
using System.Collections.Generic;
using System.IO;
using SaferTogether.UnityClient;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace SaferTogether.UnityClient.Editor
{
    /// <summary>
    /// Imports the user-provided avatar PNG pack and turns every avatar, clothing item, and accessory into prefab layers.
    /// </summary>
    public static class SaferTogetherGeneratedAvatarInstaller
    {
        private const string RootPath = "Assets/Resources/GeneratedAvatarBuilder";
        private const string RuntimeScenePath = "Assets/Scenes/RuntimeAvatar.unity";
        private const string AvatarPathRoot = RootPath + "/Avatars";
        private const string PartPathRoot = RootPath + "/Parts";
        private const string MaterialPathRoot = RootPath + "/Materials";
        private const string SourceImageAssetRoot = RootPath + "/SourceImages";
        private const string AutoGenerationSessionKey = "SaferTogether.GeneratedAvatarBuilder.AutoGenerated";
        private static readonly Vector3 AvatarLayerPosition = new Vector3(0, 1.08f, 0);
        private static readonly Vector2 AvatarLayerSize = new Vector2(3.3f, 3.3f);
        private static readonly Vector3 FemaleAvatarRootPosition = new Vector3(0.1f, 0.3f, 0f);
        private static readonly Vector3 FemaleAvatarRootScale = new Vector3(0.7f, 0.7f, 1f);
        private static readonly Vector3 DevilUndershirtPrefabPosition = new Vector3(0, -0.1f, 0);
        private static readonly Vector3 DevilUndershirtPrefabScale = new Vector3(0.9f, 0.8f, 1f);
        private static readonly Vector3 DevilSweatshirtPrefabPosition = new Vector3(0, -0.2f, 0);
        private static readonly Vector3 DevilSweatshirtPrefabScale = new Vector3(1.1f, 0.8f, 1f);
        private static readonly Vector3 DevilCargoPantsPrefabPosition = new Vector3(0, 0.2f, 0);
        private static readonly Vector3 DevilCargoPantsPrefabScale = new Vector3(0.78f, 0.85f, 1f);
        private static readonly Vector3 DevilSportsPantsPrefabPosition = new Vector3(0, 0.3f, 0);
        private static readonly Vector3 DevilSportsPantsPrefabScale = new Vector3(0.7f, 0.8f, 1f);
        private static readonly Vector3 DevilBootsPrefabPosition = new Vector3(0, -0.1f, 0);
        private static readonly Vector3 DevilBootsPrefabScale = new Vector3(1.3f, 0.7f, 1f);
        private static readonly Vector3 DevilSpaceShoesPrefabPosition = new Vector3(0, -0.1f, 0);
        private static readonly Vector3 DevilSpaceShoesPrefabScale = new Vector3(1.1f, 1f, 1f);
        private static readonly Vector3 MaleJeansPrefabPosition = new Vector3(0, -0.1f, 0);
        private static readonly Vector3 MaleJeansPrefabScale = new Vector3(1.5f, 1f, 1f);
        private static readonly Vector3 MaleCargoBluePrefabPosition = new Vector3(0, 0.05f, 0);
        private static readonly Vector3 MaleCargoBluePrefabScale = Vector3.one;
        private static readonly Vector3 MaleCargoRedPrefabPosition = new Vector3(0, 0.06f, 0);
        private static readonly Vector3 MaleCargoRedPrefabScale = new Vector3(1.1f, 1f, 1f);
        private static readonly Vector3 MaleTeeBlueWhitePrefabPosition = new Vector3(0, 0.05f, 0);
        private static readonly Vector3 MaleTeeBlueWhitePrefabScale = Vector3.one;
        private static readonly Vector3 MaleSweatshirtPrefabPosition = Vector3.zero;
        private static readonly Vector3 MaleSweatshirtPrefabScale = new Vector3(1.3f, 0.8f, 1f);
        private static readonly Vector3 MaleCompactSweatshirtPrefabScale = new Vector3(1.1f, 0.8f, 1f);
        private static readonly Vector3 FemaleTeePrefabPosition = new Vector3(0, 0.02f, 0);
        private static readonly Vector3 FemaleTeePrefabScale = new Vector3(0.9f, 0.8f, 1f);
        private static readonly Vector3 FemaleSportsPantsPrefabPosition = new Vector3(0, -0.15f, 0);
        private static readonly Vector3 FemaleSportsPantsPrefabScale = new Vector3(1.05f, 1.1f, 1f);
        private static readonly Vector3 FemaleJeansPrefabPosition = new Vector3(0, -0.12f, 0);
        private static readonly Vector3 FemaleJeansPrefabScale = new Vector3(1.1f, 1.2f, 1f);
        private static readonly Vector3 FemaleSweatshirtPrefabPosition = Vector3.zero;
        private static readonly Vector3 FemaleSweatshirtPrefabScale = new Vector3(0.95f, 0.8f, 1f);
        private static readonly Vector3 FemaleUndershirtPrefabPosition = Vector3.zero;
        private static readonly Vector3 FemaleUndershirtPrefabScale = new Vector3(0.8f, 0.7f, 1f);
        private static readonly Vector3 FemaleBootsPrefabPosition = Vector3.zero;
        private static readonly Vector3 FemaleBootsPrefabScale = new Vector3(1.4f, 1.3f, 1f);
        private static readonly Vector3 FemaleSpaceShoesPrefabPosition = Vector3.zero;
        private static readonly Vector3 FemaleSpaceShoesPrefabScale = new Vector3(1.2f, 1.5f, 1f);
        private static readonly Vector3 FemaleCrownPrefabPosition = new Vector3(-0.05f, 1f, 0f);
        private static readonly Vector3 FemaleCrownPrefabScale = new Vector3(1.1f, 1.1f, 1f);
        private static readonly Vector3 FemaleBandanaPrefabPosition = new Vector3(0.03f, 0.8f, -1f);
        private static readonly Vector3 FemaleBandanaPrefabScale = Vector3.one;
        private static readonly Vector3 FemaleGlassesPrefabPosition = new Vector3(-0.04f, 1f, 0f);
        private static readonly Vector3 FemaleGlassesPrefabScale = new Vector3(1.1f, 1.1f, 1f);
        private static readonly Vector3 FemaleMaskPrefabPosition = new Vector3(-0.05f, 1f, 0f);
        private static readonly Vector3 FemaleMaskPrefabScale = new Vector3(1.2f, 1.4f, 1f);
        private static readonly Vector3 DragonCrownPrefabPosition = new Vector3(-0.22f, 0.06f, 0f);
        private static readonly Vector3 DragonCrownPrefabScale = new Vector3(1.2f, 1.2f, 1f);
        private static readonly Vector3 DragonBandanaPrefabPosition = new Vector3(0.3f, -0.22f, 0f);
        private static readonly Vector3 DragonBandanaPrefabScale = new Vector3(2.5f, 1.3f, 1f);
        private static readonly Vector3 DragonGlassesPrefabPosition = new Vector3(-0.1f, 0f, 0f);
        private static readonly Vector3 DragonGlassesPrefabScale = new Vector3(1.1f, 1.3f, 1f);
        private static readonly Vector3 DragonMaskPrefabPosition = new Vector3(0.47f, -0.13f, 0f);
        private static readonly Vector3 DragonMaskPrefabScale = new Vector3(2.9f, 3f, 1f);
        private static readonly Vector3 MaleBootsPrefabPosition = new Vector3(0, -0.05f, 0);
        private static readonly Vector3 MaleBootsPrefabScale = new Vector3(1.5f, 0.8f, 1f);
        private static readonly Vector3 MaleSpaceShoesPrefabPosition = Vector3.zero;
        private static readonly Vector3 MaleSpaceShoesPrefabScale = new Vector3(1.3f, 1f, 1f);
        private static readonly Vector3 MaleGlassesPrefabPosition = new Vector3(0.02f, 0.25f, 0);
        private static readonly Vector3 MaleGlassesPrefabScale = new Vector3(0.85f, 1f, 1f);
        private static readonly Vector3 MaleBandanaPrefabPosition = new Vector3(0.07f, 0.05f, -1f);
        private static readonly Vector3 MaleBandanaPrefabScale = new Vector3(0.8f, 0.8f, 1f);
        private static readonly Vector3 MaleMaskPrefabPosition = new Vector3(0.015f, 0.25f, 0);
        private static readonly Vector3 MaleMaskPrefabScale = new Vector3(1f, 1.5f, 1f);
        private static readonly Vector3 DevilBandanaPrefabPosition = new Vector3(0.06f, -0.4f, 0);
        private static readonly Vector3 DevilBandanaPrefabScale = new Vector3(0.88f, 0.7f, 1f);
        private static readonly Vector3 DevilGlassesPrefabPosition = new Vector3(0, -0.1f, 0);
        private static readonly Vector3 DevilGlassesPrefabScale = new Vector3(1.4f, 1.5f, 1f);
        private static readonly Vector3 DevilMaskPrefabPosition = new Vector3(0, -0.06f, 0);
        private static readonly Vector3 DevilMaskPrefabScale = new Vector3(2f, 2.5f, 1f);
        private static readonly Vector3 DevilShirtLayerPosition = new Vector3(0, 0.3750001f, 0);
        private static readonly Vector2 DevilShirtLayerSize = new Vector2(9.166666f, 8.25f);

        private static readonly string[] ClothingColorIds =
        {
            CharacterAvatarOptions.Black,
            CharacterAvatarOptions.Blue,
            CharacterAvatarOptions.Green,
            CharacterAvatarOptions.Red,
            CharacterAvatarOptions.White,
            CharacterAvatarOptions.Yellow
        };

        private static readonly string[] ClothingColorNames =
        {
            "Black",
            "Blue",
            "Green",
            "Red",
            "White",
            "Yellow"
        };

        private static readonly StyleSource[] ShirtSources =
        {
            new StyleSource(CharacterAvatarOptions.Tee, "T-shirts", "T-shirts"),
            new StyleSource(CharacterAvatarOptions.Sweatshirt, "Sweatshirt", "Sweatshirt"),
            new StyleSource(CharacterAvatarOptions.Undershirt, "Undershirt", "Undershirt")
        };

        private static readonly StyleSource[] PantsSources =
        {
            new StyleSource(CharacterAvatarOptions.Cargo, "Cargo pants", "Cargo pants"),
            new StyleSource(CharacterAvatarOptions.SportsPants, "Sports pants", "Sports pants")
        };

        private static readonly StyleSource[] ShoeSources =
        {
            new StyleSource(CharacterAvatarOptions.Sneakers, "Sneakres", "Sneakres"),
            new StyleSource(CharacterAvatarOptions.Boots, "Boots", "Boots"),
            new StyleSource(CharacterAvatarOptions.SpaceShoes, "Space shoes", "Space shoes")
        };

        private static readonly AccessorySource[] AccessorySources =
        {
            new AccessorySource(CharacterAvatarOptions.Bandana, "Bandana", AvatarAttachmentSlot.Face),
            new AccessorySource(CharacterAvatarOptions.Crown, "Crown", AvatarAttachmentSlot.Hat),
            new AccessorySource(CharacterAvatarOptions.Glasses, "Glasses", AvatarAttachmentSlot.Face),
            new AccessorySource(CharacterAvatarOptions.Mask, "Mask", AvatarAttachmentSlot.Face)
        };

        [InitializeOnLoadMethod]
        private static void AutoGenerateOnce()
        {
            if (SessionState.GetBool(AutoGenerationSessionKey, false))
            {
                return;
            }

            SessionState.SetBool(AutoGenerationSessionKey, true);
            EditorApplication.delayCall += () =>
            {
                if (!File.Exists(AvatarPrefabPath(CharacterAvatarOptions.Male)) && Directory.Exists(ExternalAvatarSourcePath()))
                {
                    GenerateAssets(false);
                    InstallBuilderInOpenScene();
                }
            };
        }

        [MenuItem("SaferTogether/Generate 3D Avatar Prefabs")]
        public static void GenerateAndInstall()
        {
            GenerateAssets(true);
            InstallBuilderInRuntimeScene();
        }

        public static void GenerateAssets(bool overwrite)
        {
            if (overwrite)
            {
                DeleteGeneratedCatalogFolders();
            }

            EnsureFolders();
            ImportSourceImages();
            CreateAvatarPrefabs(overwrite);
            CreateClothingPrefabs("shirts", "Shirts", ShirtSources, AvatarAttachmentSlot.Shirt, new Vector2(1.48f, 1.48f), overwrite);
            CreatePantsPrefabs(overwrite);
            CreateClothingPrefabs("shoes", "Shoes", ShoeSources, AvatarAttachmentSlot.Shoes, new Vector2(1.08f, 1.08f), overwrite);
            CreateAccessoryPrefabs(overwrite);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        public static void InstallBuilderInOpenScene()
        {
            Scene scene = SceneManager.GetActiveScene();

            if (!scene.IsValid())
            {
                return;
            }

            AvatarBuilder builder = UnityEngine.Object.FindAnyObjectByType<AvatarBuilder>();

            if (builder == null)
            {
                GameObject builderObject = new GameObject("AvatarBuilder");
                builder = builderObject.AddComponent<AvatarBuilder>();
            }

            Transform previewRoot = builder.transform.Find("AvatarPreviewRoot");

            if (previewRoot == null)
            {
                previewRoot = new GameObject("AvatarPreviewRoot").transform;
                previewRoot.SetParent(builder.transform, false);
            }

            builder.avatarRoot = previewRoot;
            builder.resourcesRoot = "GeneratedAvatarBuilder";
            builder.instantiateAvatarPrefabs = true;
            builder.maleAvatar = LoadAvatar(CharacterAvatarOptions.Male);
            builder.femaleAvatar = LoadAvatar(CharacterAvatarOptions.Female);
            builder.dragonAvatar = LoadAvatar(CharacterAvatarOptions.Dragon);
            builder.devilAvatar = LoadAvatar(CharacterAvatarOptions.Devil);
            builder.accessoryPrefabs = BuildAccessoryCatalog();
            builder.shirtPrefabs = BuildColorCatalog("Shirts", AvatarAttachmentSlot.Shirt, CharacterAvatarOptions.Tops);
            builder.pantsPrefabs = BuildColorCatalog("Pants", AvatarAttachmentSlot.Pants, CharacterAvatarOptions.Bottoms);
            builder.shoePrefabs = BuildColorCatalog("Shoes", AvatarAttachmentSlot.Shoes, CharacterAvatarOptions.Shoes);

            EditorUtility.SetDirty(builder);

            if (!string.IsNullOrEmpty(scene.path))
            {
                EditorSceneManager.MarkSceneDirty(scene);
                EditorSceneManager.SaveScene(scene);
            }
        }

        public static void InstallBuilderInRuntimeScene()
        {
            EnsureRuntimeScene();
            EditorSceneManager.OpenScene(RuntimeScenePath, OpenSceneMode.Single);
            InstallBuilderInOpenScene();
        }

        private static void EnsureRuntimeScene()
        {
            if (File.Exists(RuntimeScenePath))
            {
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(RuntimeScenePath));
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);
            EditorSceneManager.SaveScene(scene, RuntimeScenePath);
            AssetDatabase.Refresh();
        }

        private static void CreateAvatarPrefabs(bool overwrite)
        {
            foreach (string species in CharacterAvatarOptions.Species)
            {
                string fileName = char.ToUpperInvariant(species[0]) + species.Substring(1) + ".png";
                string texturePath = SourceImageAssetRoot + "/" + species + "/" + fileName;
                GameObject root = AvatarRoot(species);
                root.transform.localPosition = AvatarRootPositionFor(species);
                root.transform.localScale = AvatarRootScaleFor(species);
                AddTexturedPlane(root.transform, "Base", texturePath, AvatarLayerPosition + new Vector3(0, 0, 0.03f), AvatarLayerSize, "avatar-" + species, false, true);
                AddAttachmentSet(root, ProfileFor(species));
                SavePrefab(root, AvatarPrefabPath(species), overwrite);
            }
        }

        private static void CreateClothingPrefabs(string sourceCategory, string prefabCategory, StyleSource[] sources, AvatarAttachmentSlot slot, Vector2 size, bool overwrite)
        {
            foreach (string species in CharacterAvatarOptions.Species)
            {
                if (!UsesClothing(species))
                {
                    continue;
                }

                foreach (StyleSource source in sources)
                {
                    for (int index = 0; index < ClothingColorIds.Length; index++)
                    {
                        string colorId = ClothingColorIds[index];
                        string colorName = ClothingColorNames[index];
                        string texturePath = ColoredSourcePath(species, sourceCategory, source.folder, source.filePrefix, colorName);
                        SaveImagePart(species, prefabCategory, source.id, colorId, slot, texturePath, PartSize(species, prefabCategory, source.id, size), overwrite);
                    }
                }
            }
        }

        private static void CreatePantsPrefabs(bool overwrite)
        {
            CreateClothingPrefabs("pants", "Pants", PantsSources, AvatarAttachmentSlot.Pants, new Vector2(1.3f, 1.3f), overwrite);

            foreach (string species in CharacterAvatarOptions.Species)
            {
                if (!UsesClothing(species))
                {
                    continue;
                }

                string texturePath = SourceImageAssetRoot + "/" + species + "/pants/Jeans/Jeans.png";
                SaveImagePart(species, "Pants", CharacterAvatarOptions.Jeans, CharacterAvatarOptions.Denim, AvatarAttachmentSlot.Pants, texturePath, PartSize(species, "Pants", CharacterAvatarOptions.Jeans, new Vector2(1.28f, 1.28f)), overwrite);
            }
        }

        private static void CreateAccessoryPrefabs(bool overwrite)
        {
            foreach (string species in CharacterAvatarOptions.Species)
            {
                foreach (AccessorySource source in AccessorySources)
                {
                    string texturePath = SourceImageAssetRoot + "/" + species + "/accesories/" + source.fileName + ".png";
                    GameObject root = PartRoot(source.id);
                    ApplyAccessoryPrefabTransform(root, species, source.id);
                    AddTexturedPlane(root.transform, source.id, texturePath, AccessoryOffset(species, source.id), AccessorySize(species, source.id), "accessory-" + species + "-" + source.id, true, true);
                    SavePrefab(root, PartPrefabPath("Accessories", species, source.id), overwrite);
                }
            }
        }

        private static void SaveImagePart(string species, string category, string id, string color, AvatarAttachmentSlot slot, string texturePath, Vector2 size, bool overwrite)
        {
            GameObject root = PartRoot(id + "-" + color);
            if (UsesDevilUndershirtPrefabTransform(species, category, id))
            {
                root.transform.localPosition = DevilUndershirtPrefabPosition;
                root.transform.localScale = DevilUndershirtPrefabScale;
            }
            else if (UsesDevilSweatshirtPrefabTransform(species, category, id))
            {
                root.transform.localPosition = DevilSweatshirtPrefabPosition;
                root.transform.localScale = DevilSweatshirtPrefabScale;
            }
            else if (UsesDevilCargoPantsPrefabTransform(species, category, id))
            {
                root.transform.localPosition = DevilCargoPantsPrefabPosition;
                root.transform.localScale = DevilCargoPantsPrefabScale;
            }
            else if (UsesDevilSportsPantsPrefabTransform(species, category, id))
            {
                root.transform.localPosition = DevilSportsPantsPrefabPosition;
                root.transform.localScale = DevilSportsPantsPrefabScale;
            }
            else if (UsesDevilBootsPrefabTransform(species, category, id))
            {
                root.transform.localPosition = DevilBootsPrefabPosition;
                root.transform.localScale = DevilBootsPrefabScale;
            }
            else if (UsesDevilSpaceShoesPrefabTransform(species, category, id))
            {
                root.transform.localPosition = DevilSpaceShoesPrefabPosition;
                root.transform.localScale = DevilSpaceShoesPrefabScale;
            }
            else if (UsesMaleJeansPrefabTransform(species, category, id))
            {
                root.transform.localPosition = MaleJeansPrefabPosition;
                root.transform.localScale = MaleJeansPrefabScale;
            }
            else if (UsesMaleCargoBluePrefabTransform(species, category, id, color))
            {
                root.transform.localPosition = MaleCargoBluePrefabPosition;
                root.transform.localScale = MaleCargoBluePrefabScale;
            }
            else if (UsesMaleCargoRedPrefabTransform(species, category, id, color))
            {
                root.transform.localPosition = MaleCargoRedPrefabPosition;
                root.transform.localScale = MaleCargoRedPrefabScale;
            }
            else if (UsesMaleTeeBlueWhitePrefabTransform(species, category, id, color))
            {
                root.transform.localPosition = MaleTeeBlueWhitePrefabPosition;
                root.transform.localScale = MaleTeeBlueWhitePrefabScale;
            }
            else if (UsesMaleSweatshirtPrefabTransform(species, category, id))
            {
                root.transform.localPosition = MaleSweatshirtPrefabPosition;
                root.transform.localScale = MaleSweatshirtPrefabScaleForColor(color);
            }
            else if (UsesFemaleTeePrefabTransform(species, category, id, color))
            {
                root.transform.localPosition = FemaleTeePrefabPosition;
                root.transform.localScale = FemaleTeePrefabScale;
            }
            else if (UsesFemaleSportsPantsPrefabTransform(species, category, id))
            {
                root.transform.localPosition = FemaleSportsPantsPrefabPosition;
                root.transform.localScale = FemaleSportsPantsPrefabScale;
            }
            else if (UsesFemaleJeansPrefabTransform(species, category, id))
            {
                root.transform.localPosition = FemaleJeansPrefabPosition;
                root.transform.localScale = FemaleJeansPrefabScale;
            }
            else if (UsesFemaleSweatshirtPrefabTransform(species, category, id))
            {
                root.transform.localPosition = FemaleSweatshirtPrefabPosition;
                root.transform.localScale = FemaleSweatshirtPrefabScale;
            }
            else if (UsesFemaleUndershirtPrefabTransform(species, category, id))
            {
                root.transform.localPosition = FemaleUndershirtPrefabPosition;
                root.transform.localScale = FemaleUndershirtPrefabScale;
            }
            else if (UsesFemaleBootsPrefabTransform(species, category, id))
            {
                root.transform.localPosition = FemaleBootsPrefabPosition;
                root.transform.localScale = FemaleBootsPrefabScale;
            }
            else if (UsesFemaleSpaceShoesPrefabTransform(species, category, id))
            {
                root.transform.localPosition = FemaleSpaceShoesPrefabPosition;
                root.transform.localScale = FemaleSpaceShoesPrefabScale;
            }
            else if (UsesMaleBootsPrefabTransform(species, category, id))
            {
                root.transform.localPosition = MaleBootsPrefabPosition;
                root.transform.localScale = MaleBootsPrefabScale;
            }
            else if (UsesMaleSpaceShoesPrefabTransform(species, category, id))
            {
                root.transform.localPosition = MaleSpaceShoesPrefabPosition;
                root.transform.localScale = MaleSpaceShoesPrefabScale;
            }

            bool fullCanvasLayer = UsesFullCanvasClothingLayer(species, category, id);
            Vector3 position = fullCanvasLayer ? FullCanvasClothingOffset(species, slot) : Vector3.zero;
            AddTexturedPlane(root.transform, id, texturePath, position, fullCanvasLayer ? FullCanvasLayerSize(species, slot) : size, "part-" + category.ToLowerInvariant() + "-" + species + "-" + id + "-" + color, !fullCanvasLayer, !fullCanvasLayer);
            SavePrefab(root, PartPrefabPath(category, species, id + "-" + color), overwrite);
        }

        private static void AddTexturedPlane(Transform parent, string name, string texturePath, Vector3 position, Vector2 size, string materialName, bool centerVisiblePixels, bool preserveAspect)
        {
            Texture2D texture = LoadTexture(texturePath);
            Vector2 renderSize = preserveAspect ? SizeWithTextureAspect(texture, size) : size;
            GameObject quad = GameObject.CreatePrimitive(PrimitiveType.Quad);
            quad.name = name;
            quad.transform.SetParent(parent, false);
            quad.transform.localPosition = position + (centerVisiblePixels ? VisiblePixelOffset(texture, renderSize) : Vector3.zero);
            quad.transform.localRotation = Quaternion.identity;
            quad.transform.localScale = new Vector3(renderSize.x, renderSize.y, 1f);

            Renderer renderer = quad.GetComponent<Renderer>();
            renderer.sharedMaterial = MaterialForTexture(materialName, texture);

            Collider collider = quad.GetComponent<Collider>();
            if (collider != null)
            {
                UnityEngine.Object.DestroyImmediate(collider);
            }

        }

        private static Vector2 SizeWithTextureAspect(Texture2D texture, Vector2 requestedSize)
        {
            if (texture == null || texture.width <= 0 || texture.height <= 0)
            {
                return requestedSize;
            }

            return new Vector2(requestedSize.x, requestedSize.x * texture.height / texture.width);
        }

        private static Vector3 VisiblePixelOffset(Texture2D texture, Vector2 renderSize)
        {
            if (texture == null)
            {
                return Vector3.zero;
            }

            Color32[] pixels = texture.GetPixels32();
            int minX = texture.width;
            int minY = texture.height;
            int maxX = -1;
            int maxY = -1;

            // Aligns layers by the center of their non-transparent artwork, so PNG padding does not move clothes/accessories.
            for (int y = 0; y < texture.height; y++)
            {
                int rowStart = y * texture.width;

                for (int x = 0; x < texture.width; x++)
                {
                    if (pixels[rowStart + x].a <= 8)
                    {
                        continue;
                    }

                    minX = Mathf.Min(minX, x);
                    minY = Mathf.Min(minY, y);
                    maxX = Mathf.Max(maxX, x);
                    maxY = Mathf.Max(maxY, y);
                }
            }

            if (maxX < minX || maxY < minY)
            {
                return Vector3.zero;
            }

            float centerX = (minX + maxX + 1f) * 0.5f / texture.width;
            float centerY = (minY + maxY + 1f) * 0.5f / texture.height;

            return new Vector3(
                (0.5f - centerX) * renderSize.x,
                (0.5f - centerY) * renderSize.y,
                0
            );
        }

        private static Texture2D LoadTexture(string assetPath)
        {
            TextureImporter importer = AssetImporter.GetAtPath(assetPath) as TextureImporter;

            if (importer == null)
            {
                throw new FileNotFoundException("Avatar image asset was not imported: " + assetPath);
            }

            importer.textureType = TextureImporterType.Default;
            importer.alphaIsTransparency = true;
            importer.isReadable = true;
            importer.mipmapEnabled = false;
            importer.npotScale = TextureImporterNPOTScale.None;
            importer.wrapMode = TextureWrapMode.Clamp;
            importer.SaveAndReimport();

            Texture2D texture = AssetDatabase.LoadAssetAtPath<Texture2D>(assetPath);

            if (texture == null)
            {
                throw new FileNotFoundException("Avatar image asset could not be loaded: " + assetPath);
            }

            return texture;
        }

        private static Material MaterialForTexture(string name, Texture texture)
        {
            string path = MaterialPathRoot + "/" + Sanitize(name) + ".mat";
            Material material = AssetDatabase.LoadAssetAtPath<Material>(path);
            Shader shader = Shader.Find("Sprites/Default")
                ?? Shader.Find("Unlit/Transparent")
                ?? Shader.Find("Standard");

            if (material == null)
            {
                material = new Material(shader)
                {
                    name = Sanitize(name)
                };
                AssetDatabase.CreateAsset(material, path);
            }
            else
            {
                material.shader = shader;
            }

            material.SetTexture("_MainTex", texture);
            material.mainTexture = texture;
            material.color = Color.white;
            EditorUtility.SetDirty(material);
            return material;
        }

        private static string ColoredSourcePath(string species, string category, string folder, string filePrefix, string colorName)
        {
            string folderAssetPath = SourceImageAssetRoot + "/" + species + "/" + category + "/" + folder;
            string exactPath = folderAssetPath + "/" + filePrefix + " " + colorName + ".png";

            if (File.Exists(AssetPathToFullPath(exactPath)))
            {
                return exactPath;
            }

            string folderPath = AssetPathToFullPath(folderAssetPath);
            string[] matches = Directory.GetFiles(folderPath, "*" + colorName + ".png", SearchOption.TopDirectoryOnly);

            if (matches.Length == 0)
            {
                throw new FileNotFoundException("Could not find " + colorName + " image in " + folderAssetPath);
            }

            return FullPathToAssetPath(matches[0]);
        }

        private static AvatarProfile ProfileFor(string species)
        {
            switch (species)
            {
                case CharacterAvatarOptions.Dragon:
                    return new AvatarProfile(
                        new Vector3(-0.22f, 1.78f, -0.1f),
                        new Vector3(-0.03f, 2.22f, -0.11f),
                        new Vector3(-0.03f, 2.18f, -0.11f),
                        AvatarLayerPosition + new Vector3(0, 0, -0.12f),
                        Vector3.one,
                        AvatarLayerPosition + new Vector3(0, 0, -0.13f),
                        Vector3.one,
                        AvatarLayerPosition + new Vector3(0, 0, -0.14f),
                        Vector3.one
                    );
                case CharacterAvatarOptions.Devil:
                    return new AvatarProfile(
                        new Vector3(0, 1.78f, -0.16f),
                        new Vector3(0, 2.34f, -0.17f),
                        new Vector3(0, 2.28f, -0.17f),
                        new Vector3(0, 1f, -0.12f),
                        new Vector3(0.124f, 0.14f, 1f),
                        new Vector3(0, 0.34f, -0.13f),
                        new Vector3(0.86f, 0.7f, 1f),
                        new Vector3(0, 0, -0.14f),
                        Vector3.one
                    );
                case CharacterAvatarOptions.Female:
                    return new AvatarProfile(
                        new Vector3(0, 1.78f, -0.1f),
                        new Vector3(0, 2.32f, -0.11f),
                        new Vector3(0, 2.25f, -0.11f),
                        new Vector3(-0.05f, 1.8f, -0.12f),
                        Vector3.one,
                        new Vector3(-0.05f, 0.55f, -0.13f),
                        new Vector3(1.45f, 1f, 1f),
                        new Vector3(-0.06f, -1f, -0.14f),
                        new Vector3(0.9f, 0.6f, 1f)
                    );
                case CharacterAvatarOptions.Human:
                case CharacterAvatarOptions.Male:
                    return new AvatarProfile(
                        new Vector3(0, 1.78f, -0.1f),
                        new Vector3(0, 2.6f, -0.11f),
                        new Vector3(0, 2.25f, -0.11f),
                        new Vector3(-0.01f, 1.35f, -0.12f),
                        new Vector3(0.78f, 0.85f, 1f),
                        new Vector3(-0.01f, 0.6f, -0.13f),
                        new Vector3(0.8f, 1f, 1f),
                        new Vector3(-0.015f, -0.24f, -0.14f),
                        new Vector3(0.8f, 0.6f, 1f)
                    );
                default:
                    return new AvatarProfile(
                        new Vector3(0, 1.78f, -0.1f),
                        new Vector3(0, 2.32f, -0.11f),
                        new Vector3(0, 2.25f, -0.11f),
                        new Vector3(-0.01f, 1.338f, -0.12f),
                        new Vector3(0.78f, 0.8f, 1f),
                        new Vector3(-0.01f, 0.35f, -0.13f),
                        new Vector3(1.38f, 1f, 1f),
                        new Vector3(0, -0.75f, -0.14f),
                        Vector3.one
                    );
            }
        }

        private static Vector2 PartSize(string species, string category, string id, Vector2 fallback)
        {
            if (species == CharacterAvatarOptions.Devil)
            {
                switch (category)
                {
                    case "Pants":
                        return new Vector2(1.58f, 1.58f);
                    case "Shoes":
                        return new Vector2(1.15f, 1.15f);
                }
            }

            switch (category)
            {
                case "Shirts":
                    switch (id)
                    {
                        case CharacterAvatarOptions.Sweatshirt:
                            return new Vector2(1.56f, 1.56f);
                        case CharacterAvatarOptions.Undershirt:
                            return new Vector2(1.32f, 1.32f);
                        default:
                            return fallback;
                    }
                case "Pants":
                    switch (id)
                    {
                        case CharacterAvatarOptions.Jeans:
                            return new Vector2(1.28f, 1.28f);
                        case CharacterAvatarOptions.SportsPants:
                            return new Vector2(1.34f, 1.34f);
                        default:
                            return new Vector2(1.36f, 1.36f);
                    }
                case "Shoes":
                    switch (id)
                    {
                        case CharacterAvatarOptions.Boots:
                            return new Vector2(1.16f, 1.16f);
                        case CharacterAvatarOptions.SpaceShoes:
                            return new Vector2(1.18f, 1.18f);
                        default:
                            return new Vector2(1.08f, 1.08f);
                    }
                default:
                    return fallback;
            }
        }

        private static bool UsesFullCanvasClothingLayer(string species, string category, string id)
        {
            if (species != CharacterAvatarOptions.Devil)
            {
                return false;
            }

            return category == "Shirts";
        }

        private static bool UsesDevilUndershirtPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Devil
                && category == "Shirts"
                && id == CharacterAvatarOptions.Undershirt;
        }

        private static bool UsesDevilSweatshirtPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Devil
                && category == "Shirts"
                && id == CharacterAvatarOptions.Sweatshirt;
        }

        private static bool UsesDevilCargoPantsPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Devil
                && category == "Pants"
                && id == CharacterAvatarOptions.Cargo;
        }

        private static bool UsesDevilSportsPantsPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Devil
                && category == "Pants"
                && id == CharacterAvatarOptions.SportsPants;
        }

        private static bool UsesDevilBootsPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Devil
                && category == "Shoes"
                && id == CharacterAvatarOptions.Boots;
        }

        private static bool UsesDevilSpaceShoesPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Devil
                && category == "Shoes"
                && id == CharacterAvatarOptions.SpaceShoes;
        }

        private static bool UsesMaleJeansPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Male
                && category == "Pants"
                && id == CharacterAvatarOptions.Jeans;
        }

        private static bool UsesMaleCargoBluePrefabTransform(string species, string category, string id, string color)
        {
            return species == CharacterAvatarOptions.Male
                && category == "Pants"
                && id == CharacterAvatarOptions.Cargo
                && color == CharacterAvatarOptions.Blue;
        }

        private static bool UsesMaleCargoRedPrefabTransform(string species, string category, string id, string color)
        {
            return species == CharacterAvatarOptions.Male
                && category == "Pants"
                && id == CharacterAvatarOptions.Cargo
                && color == CharacterAvatarOptions.Red;
        }

        private static bool UsesMaleTeeBlueWhitePrefabTransform(string species, string category, string id, string color)
        {
            return species == CharacterAvatarOptions.Male
                && category == "Shirts"
                && id == CharacterAvatarOptions.Tee
                && (color == CharacterAvatarOptions.Blue
                    || color == CharacterAvatarOptions.White);
        }

        private static bool UsesMaleSweatshirtPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Male
                && category == "Shirts"
                && id == CharacterAvatarOptions.Sweatshirt;
        }

        private static Vector3 MaleSweatshirtPrefabScaleForColor(string color)
        {
            switch (color)
            {
                case CharacterAvatarOptions.Black:
                case CharacterAvatarOptions.Blue:
                case CharacterAvatarOptions.Red:
                case CharacterAvatarOptions.Yellow:
                    return MaleCompactSweatshirtPrefabScale;
                default:
                    return MaleSweatshirtPrefabScale;
            }
        }

        private static bool UsesFemaleTeePrefabTransform(string species, string category, string id, string color)
        {
            return species == CharacterAvatarOptions.Female
                && category == "Shirts"
                && id == CharacterAvatarOptions.Tee
                && (color == CharacterAvatarOptions.Red
                    || color == CharacterAvatarOptions.Blue
                    || color == CharacterAvatarOptions.White
                    || color == CharacterAvatarOptions.Yellow);
        }

        private static bool UsesFemaleSportsPantsPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Female
                && category == "Pants"
                && id == CharacterAvatarOptions.SportsPants;
        }

        private static bool UsesFemaleJeansPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Female
                && category == "Pants"
                && id == CharacterAvatarOptions.Jeans;
        }

        private static bool UsesFemaleSweatshirtPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Female
                && category == "Shirts"
                && id == CharacterAvatarOptions.Sweatshirt;
        }

        private static bool UsesFemaleUndershirtPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Female
                && category == "Shirts"
                && id == CharacterAvatarOptions.Undershirt;
        }

        private static bool UsesFemaleBootsPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Female
                && category == "Shoes"
                && id == CharacterAvatarOptions.Boots;
        }

        private static bool UsesFemaleSpaceShoesPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Female
                && category == "Shoes"
                && id == CharacterAvatarOptions.SpaceShoes;
        }

        private static bool UsesMaleBootsPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Male
                && category == "Shoes"
                && id == CharacterAvatarOptions.Boots;
        }

        private static bool UsesMaleSpaceShoesPrefabTransform(string species, string category, string id)
        {
            return species == CharacterAvatarOptions.Male
                && category == "Shoes"
                && id == CharacterAvatarOptions.SpaceShoes;
        }

        private static bool UsesClothing(string species)
        {
            return species != CharacterAvatarOptions.Dragon;
        }

        private static void ApplyAccessoryPrefabTransform(GameObject root, string species, string id)
        {
            // Species-specific accessory roots keep the large exported prefabs aligned with the avatar silhouette.
            if (species == CharacterAvatarOptions.Dragon)
            {
                switch (id)
                {
                    case CharacterAvatarOptions.Crown:
                        root.transform.localPosition = DragonCrownPrefabPosition;
                        root.transform.localScale = DragonCrownPrefabScale;
                        return;
                    case CharacterAvatarOptions.Bandana:
                        root.transform.localPosition = DragonBandanaPrefabPosition;
                        root.transform.localScale = DragonBandanaPrefabScale;
                        return;
                    case CharacterAvatarOptions.Glasses:
                        root.transform.localPosition = DragonGlassesPrefabPosition;
                        root.transform.localScale = DragonGlassesPrefabScale;
                        return;
                    case CharacterAvatarOptions.Mask:
                        root.transform.localPosition = DragonMaskPrefabPosition;
                        root.transform.localScale = DragonMaskPrefabScale;
                        return;
                }
            }

            if (species == CharacterAvatarOptions.Female)
            {
                switch (id)
                {
                    case CharacterAvatarOptions.Crown:
                        root.transform.localPosition = FemaleCrownPrefabPosition;
                        root.transform.localScale = FemaleCrownPrefabScale;
                        return;
                    case CharacterAvatarOptions.Bandana:
                        root.transform.localPosition = FemaleBandanaPrefabPosition;
                        root.transform.localScale = FemaleBandanaPrefabScale;
                        return;
                    case CharacterAvatarOptions.Glasses:
                        root.transform.localPosition = FemaleGlassesPrefabPosition;
                        root.transform.localScale = FemaleGlassesPrefabScale;
                        return;
                    case CharacterAvatarOptions.Mask:
                        root.transform.localPosition = FemaleMaskPrefabPosition;
                        root.transform.localScale = FemaleMaskPrefabScale;
                        return;
                }
            }

            if (species == CharacterAvatarOptions.Male)
            {
                switch (id)
                {
                    case CharacterAvatarOptions.Glasses:
                        root.transform.localPosition = MaleGlassesPrefabPosition;
                        root.transform.localScale = MaleGlassesPrefabScale;
                        return;
                    case CharacterAvatarOptions.Bandana:
                        root.transform.localPosition = MaleBandanaPrefabPosition;
                        root.transform.localScale = MaleBandanaPrefabScale;
                        return;
                    case CharacterAvatarOptions.Mask:
                        root.transform.localPosition = MaleMaskPrefabPosition;
                        root.transform.localScale = MaleMaskPrefabScale;
                        return;
                }
            }

            if (species != CharacterAvatarOptions.Devil)
            {
                return;
            }

            switch (id)
            {
                case CharacterAvatarOptions.Bandana:
                    root.transform.localPosition = DevilBandanaPrefabPosition;
                    root.transform.localScale = DevilBandanaPrefabScale;
                    break;
                case CharacterAvatarOptions.Glasses:
                    root.transform.localPosition = DevilGlassesPrefabPosition;
                    root.transform.localScale = DevilGlassesPrefabScale;
                    break;
                case CharacterAvatarOptions.Mask:
                    root.transform.localPosition = DevilMaskPrefabPosition;
                    root.transform.localScale = DevilMaskPrefabScale;
                    break;
            }
        }

        private static Vector3 FullCanvasClothingOffset(string species, AvatarAttachmentSlot slot)
        {
            if (UsesDevilShirtPointScale(species, slot))
            {
                return DevilShirtLayerPosition;
            }

            AvatarProfile profile = ProfileFor(species);
            Vector3 attachmentPosition = AttachmentPositionFor(profile, slot);
            Vector3 attachmentScale = AttachmentScaleFor(profile, slot);
            Vector3 canvasPosition = new Vector3(AvatarLayerPosition.x, AvatarLayerPosition.y, attachmentPosition.z);

            // Full-avatar clothing PNGs are still parented to their slot, so this cancels the slot offset back to the avatar canvas.
            return new Vector3(
                DivideByScale(canvasPosition.x - attachmentPosition.x, attachmentScale.x),
                DivideByScale(canvasPosition.y - attachmentPosition.y, attachmentScale.y),
                canvasPosition.z - attachmentPosition.z
            );
        }

        private static Vector2 FullCanvasLayerSize(string species, AvatarAttachmentSlot slot)
        {
            if (UsesDevilShirtPointScale(species, slot))
            {
                return DevilShirtLayerSize;
            }

            AvatarProfile profile = ProfileFor(species);
            Vector3 attachmentScale = AttachmentScaleFor(profile, slot);
            return new Vector2(
                DivideByScale(AvatarLayerSize.x, attachmentScale.x),
                DivideByScale(AvatarLayerSize.y, attachmentScale.y)
            );
        }

        private static bool UsesDevilShirtPointScale(string species, AvatarAttachmentSlot slot)
        {
            return species == CharacterAvatarOptions.Devil
                && slot == AvatarAttachmentSlot.Shirt;
        }

        private static Vector3 AttachmentPositionFor(AvatarProfile profile, AvatarAttachmentSlot slot)
        {
            switch (slot)
            {
                case AvatarAttachmentSlot.Pants:
                    return profile.pants;
                case AvatarAttachmentSlot.Shoes:
                case AvatarAttachmentSlot.LeftShoe:
                case AvatarAttachmentSlot.RightShoe:
                    return profile.shoes;
                default:
                    return profile.shirt;
            }
        }

        private static Vector3 AttachmentScaleFor(AvatarProfile profile, AvatarAttachmentSlot slot)
        {
            switch (slot)
            {
                case AvatarAttachmentSlot.Pants:
                    return profile.pantsScale;
                case AvatarAttachmentSlot.Shoes:
                case AvatarAttachmentSlot.LeftShoe:
                case AvatarAttachmentSlot.RightShoe:
                    return profile.shoesScale;
                default:
                    return profile.shirtScale;
            }
        }

        private static float DivideByScale(float value, float scale)
        {
            return Mathf.Approximately(scale, 0f) ? value : value / scale;
        }

        private static Vector2 AccessorySize(string species, string id)
        {
            if (species == CharacterAvatarOptions.Dragon)
            {
                switch (id)
                {
                    case CharacterAvatarOptions.Crown:
                        return new Vector2(0.82f, 0.82f);
                    case CharacterAvatarOptions.Bandana:
                        return new Vector2(0.72f, 0.72f);
                    case CharacterAvatarOptions.Glasses:
                        return new Vector2(0.9f, 0.9f);
                    case CharacterAvatarOptions.Mask:
                        return new Vector2(1.18f, 1.18f);
                }
            }

            if (species == CharacterAvatarOptions.Devil)
            {
                switch (id)
                {
                    case CharacterAvatarOptions.Crown:
                        return new Vector2(0.88f, 0.88f);
                    case CharacterAvatarOptions.Bandana:
                        return new Vector2(0.88f, 0.88f);
                    case CharacterAvatarOptions.Glasses:
                        return new Vector2(0.78f, 0.78f);
                    case CharacterAvatarOptions.Mask:
                        return new Vector2(1.04f, 1.04f);
                }
            }

            switch (id)
            {
                case CharacterAvatarOptions.Crown:
                    return new Vector2(1.0f, 1.0f);
                case CharacterAvatarOptions.Bandana:
                    return new Vector2(1.05f, 1.05f);
                case CharacterAvatarOptions.Glasses:
                    return new Vector2(0.86f, 0.86f);
                case CharacterAvatarOptions.Mask:
                    return new Vector2(1.28f, 1.28f);
                default:
                    return new Vector2(0.8f, 0.8f);
            }
        }

        private static Vector3 AccessoryOffset(string species, string id)
        {
            if (species == CharacterAvatarOptions.Dragon)
            {
                switch (id)
                {
                    case CharacterAvatarOptions.Crown:
                        return new Vector3(0, 0.02f, 0);
                    case CharacterAvatarOptions.Bandana:
                        return new Vector3(-0.05f, -0.35f, 0);
                    case CharacterAvatarOptions.Glasses:
                        return new Vector3(0, 0.08f, 0);
                    case CharacterAvatarOptions.Mask:
                        return new Vector3(-0.08f, -0.15f, 0);
                }
            }

            if (species == CharacterAvatarOptions.Devil)
            {
                switch (id)
                {
                    case CharacterAvatarOptions.Crown:
                        return new Vector3(0, 0.05f, 0);
                    case CharacterAvatarOptions.Bandana:
                        return new Vector3(0, -0.2f, 0);
                    case CharacterAvatarOptions.Glasses:
                        return new Vector3(0, 0.04f, 0);
                    case CharacterAvatarOptions.Mask:
                        return new Vector3(0, -0.08f, 0);
                }
            }

            switch (id)
            {
                case CharacterAvatarOptions.Crown:
                    return new Vector3(0, 0.07f, 0);
                case CharacterAvatarOptions.Bandana:
                    return new Vector3(0, -0.22f, 0);
                case CharacterAvatarOptions.Glasses:
                    return new Vector3(0, 0.05f, 0);
                case CharacterAvatarOptions.Mask:
                    return new Vector3(0, -0.1f, 0);
                default:
                    return Vector3.zero;
            }
        }

        private static void AddAttachmentSet(GameObject root, AvatarProfile profile)
        {
            AvatarAttachmentSet set = root.AddComponent<AvatarAttachmentSet>();
            set.facePoint = Point("FacePoint", root.transform, profile.face);
            set.hatPoint = Point("HatPoint", root.transform, profile.hat);
            set.hornsPoint = Point("HornsPoint", root.transform, profile.horns);
            set.wingsPoint = Point("WingsPoint", root.transform, new Vector3(0, 1.1f, -0.1f));
            set.tailPoint = Point("TailPoint", root.transform, new Vector3(0.65f, 0.35f, -0.1f));
            set.shirtPoint = Point("ShirtPoint", root.transform, profile.shirt, profile.shirtScale);
            set.pantsPoint = Point("PantsPoint", root.transform, profile.pants, profile.pantsScale);
            set.shoesPoint = Point("ShoesPoint", root.transform, profile.shoes, profile.shoesScale);
            set.leftShoePoint = Point("LeftShoePoint", root.transform, profile.shoes + new Vector3(-0.26f, 0, 0));
            set.rightShoePoint = Point("RightShoePoint", root.transform, profile.shoes + new Vector3(0.26f, 0, 0));
        }

        private static Transform Point(string name, Transform parent, Vector3 position)
        {
            return Point(name, parent, position, Vector3.one);
        }

        private static Transform Point(string name, Transform parent, Vector3 position, Vector3 scale)
        {
            Transform point = new GameObject(name).transform;
            point.SetParent(parent, false);
            point.localPosition = position;
            point.localScale = scale;
            return point;
        }

        private static void ImportSourceImages()
        {
            string sourcePath = ExternalAvatarSourcePath();

            if (!Directory.Exists(sourcePath))
            {
                throw new DirectoryNotFoundException("Missing avatar source folder: " + sourcePath);
            }

            DeleteAssetIfExists(SourceImageAssetRoot);

            string destinationPath = AssetPathToFullPath(SourceImageAssetRoot);
            Directory.CreateDirectory(destinationPath);

            foreach (string file in Directory.GetFiles(sourcePath, "*.png", SearchOption.AllDirectories))
            {
                string relative = file.Substring(sourcePath.Length).TrimStart(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
                string destinationFile = Path.Combine(destinationPath, relative);
                Directory.CreateDirectory(Path.GetDirectoryName(destinationFile));
                File.Copy(file, destinationFile, true);
            }

            AssetDatabase.Refresh();
        }

        private static void SavePrefab(GameObject root, string path, bool overwrite)
        {
            if (!overwrite && File.Exists(path))
            {
                UnityEngine.Object.DestroyImmediate(root);
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(path));
            PrefabUtility.SaveAsPrefabAsset(root, path);
            UnityEngine.Object.DestroyImmediate(root);
        }

        private static AvatarPartPrefab[] BuildColorCatalog(string category, AvatarAttachmentSlot slot, string[] ids)
        {
            var result = new List<AvatarPartPrefab>();

            foreach (string species in CharacterAvatarOptions.Species)
            {
                if (!UsesClothing(species))
                {
                    continue;
                }

                foreach (string id in ids)
                {
                    foreach (string color in ColorsForPart(id))
                    {
                        result.Add(new AvatarPartPrefab
                        {
                            species = species,
                            id = id,
                            color = color,
                            slot = slot,
                            prefab = LoadPart(category, species, id + "-" + color)
                        });
                    }
                }
            }

            return result.ToArray();
        }

        private static AvatarPartPrefab[] BuildAccessoryCatalog()
        {
            var result = new List<AvatarPartPrefab>();

            foreach (string species in CharacterAvatarOptions.Species)
            {
                foreach (AccessorySource source in AccessorySources)
                {
                    result.Add(new AvatarPartPrefab
                    {
                        species = species,
                        id = source.id,
                        slot = source.slot,
                        prefab = LoadPart("Accessories", species, source.id)
                    });
                }
            }

            return result.ToArray();
        }

        private static string[] ColorsForPart(string id)
        {
            return id == CharacterAvatarOptions.Jeans
                ? new[] { CharacterAvatarOptions.Denim }
                : ClothingColorIds;
        }

        private static GameObject LoadAvatar(string id)
        {
            return AssetDatabase.LoadAssetAtPath<GameObject>(AvatarPrefabPath(id));
        }

        private static GameObject LoadPart(string category, string species, string id)
        {
            return AssetDatabase.LoadAssetAtPath<GameObject>(PartPrefabPath(category, species, id));
        }

        private static string AvatarPrefabPath(string id)
        {
            return AvatarPathRoot + "/" + id + ".prefab";
        }

        private static string PartPrefabPath(string category, string species, string id)
        {
            return PartPathRoot + "/" + category + "/" + species + "/" + id + ".prefab";
        }

        private static GameObject AvatarRoot(string name)
        {
            GameObject root = new GameObject(name);
            root.transform.localScale = Vector3.one;
            return root;
        }

        private static Vector3 AvatarRootScaleFor(string species)
        {
            return species == CharacterAvatarOptions.Female
                ? FemaleAvatarRootScale
                : Vector3.one;
        }

        private static Vector3 AvatarRootPositionFor(string species)
        {
            return species == CharacterAvatarOptions.Female
                ? FemaleAvatarRootPosition
                : Vector3.zero;
        }

        private static GameObject PartRoot(string name)
        {
            return new GameObject(name);
        }

        private static void DeleteGeneratedCatalogFolders()
        {
            DeleteAssetIfExists(AvatarPathRoot);
            DeleteAssetIfExists(PartPathRoot);
            DeleteAssetIfExists(MaterialPathRoot);
            DeleteAssetIfExists(SourceImageAssetRoot);
        }

        private static void DeleteAssetIfExists(string assetPath)
        {
            if (AssetDatabase.IsValidFolder(assetPath) || File.Exists(assetPath))
            {
                AssetDatabase.DeleteAsset(assetPath);
            }
        }

        private static void EnsureFolders()
        {
            EnsureFolder("Assets", "Resources");
            EnsureFolder("Assets/Resources", "GeneratedAvatarBuilder");
            EnsureFolder(RootPath, "Avatars");
            EnsureFolder(RootPath, "Parts");
            EnsureFolder(RootPath, "Materials");
            EnsureFolder(PartPathRoot, "Accessories");
            EnsureFolder(PartPathRoot, "Pants");
            EnsureFolder(PartPathRoot, "Shirts");
            EnsureFolder(PartPathRoot, "Shoes");

            foreach (string species in CharacterAvatarOptions.Species)
            {
                EnsureFolder(PartPathRoot + "/Accessories", species);

                if (UsesClothing(species))
                {
                    EnsureFolder(PartPathRoot + "/Pants", species);
                    EnsureFolder(PartPathRoot + "/Shirts", species);
                    EnsureFolder(PartPathRoot + "/Shoes", species);
                }
            }
        }

        private static void EnsureFolder(string parent, string child)
        {
            string path = parent + "/" + child;

            if (!AssetDatabase.IsValidFolder(path))
            {
                AssetDatabase.CreateFolder(parent, child);
            }
        }

        private static string ExternalAvatarSourcePath()
        {
            return Path.GetFullPath(Path.Combine(Application.dataPath, "..", "..", "Unity Avatars"));
        }

        private static string AssetPathToFullPath(string assetPath)
        {
            return Path.GetFullPath(Path.Combine(ProjectRootPath(), assetPath));
        }

        private static string FullPathToAssetPath(string fullPath)
        {
            string normalizedRoot = ProjectRootPath().Replace("\\", "/").TrimEnd('/');
            string normalizedPath = fullPath.Replace("\\", "/");
            return normalizedPath.StartsWith(normalizedRoot, StringComparison.OrdinalIgnoreCase)
                ? normalizedPath.Substring(normalizedRoot.Length + 1)
                : normalizedPath;
        }

        private static string ProjectRootPath()
        {
            return Path.GetFullPath(Path.Combine(Application.dataPath, ".."));
        }

        private static string Sanitize(string value)
        {
            char[] chars = value.ToLowerInvariant().ToCharArray();

            for (int index = 0; index < chars.Length; index++)
            {
                char c = chars[index];
                if ((c < 'a' || c > 'z') && (c < '0' || c > '9') && c != '-' && c != '_')
                {
                    chars[index] = '-';
                }
            }

            return new string(chars);
        }

        private readonly struct StyleSource
        {
            public readonly string id;
            public readonly string folder;
            public readonly string filePrefix;

            public StyleSource(string id, string folder, string filePrefix)
            {
                this.id = id;
                this.folder = folder;
                this.filePrefix = filePrefix;
            }
        }

        private readonly struct AccessorySource
        {
            public readonly string id;
            public readonly string fileName;
            public readonly AvatarAttachmentSlot slot;

            public AccessorySource(string id, string fileName, AvatarAttachmentSlot slot)
            {
                this.id = id;
                this.fileName = fileName;
                this.slot = slot;
            }
        }

        private readonly struct AvatarProfile
        {
            public readonly Vector3 face;
            public readonly Vector3 hat;
            public readonly Vector3 horns;
            public readonly Vector3 shirt;
            public readonly Vector3 shirtScale;
            public readonly Vector3 pants;
            public readonly Vector3 pantsScale;
            public readonly Vector3 shoes;
            public readonly Vector3 shoesScale;

            public AvatarProfile(Vector3 face, Vector3 hat, Vector3 horns, Vector3 shirt, Vector3 shirtScale, Vector3 pants, Vector3 pantsScale, Vector3 shoes, Vector3 shoesScale)
            {
                this.face = face;
                this.hat = hat;
                this.horns = horns;
                this.shirt = shirt;
                this.shirtScale = shirtScale;
                this.pants = pants;
                this.pantsScale = pantsScale;
                this.shoes = shoes;
                this.shoesScale = shoesScale;
            }
        }
    }
}
