using System.IO;
using SaferTogether.UnityClient;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace SaferTogether.UnityClient.Editor
{
    /// <summary>
    /// Creates generated 3D avatar prefabs and wires them into the avatar builder scene.
    /// </summary>
    public static class SaferTogetherGeneratedAvatarInstaller
    {
        private const string RootPath = "Assets/Resources/GeneratedAvatarBuilder";
        private const string RuntimeScenePath = "Assets/Scenes/RuntimeAvatar.unity";
        private const string AvatarPathRoot = RootPath + "/Avatars";
        private const string PartPathRoot = RootPath + "/Parts";
        private const string MaterialPathRoot = RootPath + "/Materials";
        private const string AutoGenerationSessionKey = "SaferTogether.GeneratedAvatarBuilder.AutoGenerated";

        [InitializeOnLoadMethod]
        private static void AutoGenerateOnce()
        {
            if (SessionState.GetBool(AutoGenerationSessionKey, false))
            {
                return;
            }

            SessionState.SetBool(AutoGenerationSessionKey, true);
            EditorApplication.delayCall += () =>
            {
                if (!File.Exists(AvatarPrefabPath(CharacterAvatarOptions.Human)))
                {
                    GenerateAssets(false);
                    InstallBuilderInOpenScene();
                }
            };
        }

        [MenuItem("SaferTogether/Generate 3D Avatar Prefabs")]
        public static void GenerateAndInstall()
        {
            GenerateAssets(true);
            InstallBuilderInRuntimeScene();
        }

        public static void GenerateAssets(bool overwrite)
        {
            EnsureFolders();
            Material skin = Material("skin", new Color32(218, 154, 105, 255));
            Material skinLight = Material("skin-light", new Color32(255, 214, 185, 255));
            Material hair = Material("hair-brown", new Color32(91, 55, 36, 255));
            Material green = Material("dragon-green", new Color32(55, 163, 74, 255));
            Material gold = Material("gold", new Color32(240, 180, 72, 255));
            Material red = Material("devil-red", new Color32(196, 67, 58, 255));
            Material white = Material("warm-white", new Color32(245, 238, 219, 255));
            Material bear = Material("bear-fur", new Color32(170, 103, 45, 255));
            Material elephant = Material("elephant-blue", new Color32(112, 159, 185, 255));
            Material dark = Material("dark-leather", new Color32(45, 35, 30, 255));

            SaveAvatar(CharacterAvatarOptions.Human, CreateHumanAvatar(skin, hair, dark), overwrite);
            SaveAvatar(CharacterAvatarOptions.Dragon, CreateDragonAvatar(green, gold, dark), overwrite);
            SaveAvatar(CharacterAvatarOptions.Bear, CreateBearAvatar(bear, skinLight, dark), overwrite);
            SaveAvatar(CharacterAvatarOptions.Elephant, CreateElephantAvatar(elephant, gold, dark), overwrite);
            SaveAvatar(CharacterAvatarOptions.Devil, CreateDevilAvatar(red, dark, gold), overwrite);
            SaveAvatar(CharacterAvatarOptions.Angel, CreateAngelAvatar(skinLight, white, gold), overwrite);

            CreateShirtPrefabs(overwrite);
            CreatePantsPrefabs(overwrite);
            CreateShoePrefabs(overwrite);
            CreateAccessoryPrefabs(overwrite);

            AssetDatabase.SaveAssets();
            AssetDatabase.Refresh();
        }

        public static void InstallBuilderInOpenScene()
        {
            Scene scene = SceneManager.GetActiveScene();

            if (!scene.IsValid())
            {
                return;
            }

            AvatarBuilder builder = Object.FindAnyObjectByType<AvatarBuilder>();

            if (builder == null)
            {
                GameObject builderObject = new GameObject("AvatarBuilder");
                builder = builderObject.AddComponent<AvatarBuilder>();
            }

            Transform previewRoot = builder.transform.Find("AvatarPreviewRoot");

            if (previewRoot == null)
            {
                previewRoot = new GameObject("AvatarPreviewRoot").transform;
                previewRoot.SetParent(builder.transform, false);
            }

            builder.avatarRoot = previewRoot;
            builder.resourcesRoot = "GeneratedAvatarBuilder";
            builder.instantiateAvatarPrefabs = true;
            builder.humanAvatar = LoadAvatar(CharacterAvatarOptions.Human);
            builder.dragonAvatar = LoadAvatar(CharacterAvatarOptions.Dragon);
            builder.bearAvatar = LoadAvatar(CharacterAvatarOptions.Bear);
            builder.elephantAvatar = LoadAvatar(CharacterAvatarOptions.Elephant);
            builder.devilAvatar = LoadAvatar(CharacterAvatarOptions.Devil);
            builder.angelAvatar = LoadAvatar(CharacterAvatarOptions.Angel);
            builder.accessoryPrefabs = BuildAccessoryCatalog();
            builder.shirtPrefabs = BuildCatalog("Shirts", AvatarAttachmentSlot.Shirt, CharacterAvatarOptions.Tops);
            builder.pantsPrefabs = BuildCatalog("Pants", AvatarAttachmentSlot.Pants, CharacterAvatarOptions.Bottoms);
            builder.shoePrefabs = BuildShoeCatalog();

            EditorUtility.SetDirty(builder);

            if (!string.IsNullOrEmpty(scene.path))
            {
                EditorSceneManager.MarkSceneDirty(scene);
                EditorSceneManager.SaveScene(scene);
            }
        }

        public static void InstallBuilderInRuntimeScene()
        {
            EnsureRuntimeScene();
            EditorSceneManager.OpenScene(RuntimeScenePath, OpenSceneMode.Single);
            InstallBuilderInOpenScene();
        }

        private static void EnsureRuntimeScene()
        {
            if (File.Exists(RuntimeScenePath))
            {
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(RuntimeScenePath));
            Scene scene = EditorSceneManager.NewScene(NewSceneSetup.DefaultGameObjects, NewSceneMode.Single);
            EditorSceneManager.SaveScene(scene, RuntimeScenePath);
            AssetDatabase.Refresh();
        }

        private static void SaveAvatar(string id, GameObject avatar, bool overwrite)
        {
            SavePrefab(avatar, AvatarPrefabPath(id), overwrite);
        }

        private static GameObject CreateHumanAvatar(Material skin, Material hair, Material dark)
        {
            GameObject root = AvatarRoot("human");
            Primitive("Body", PrimitiveType.Capsule, root.transform, new Vector3(0, 0.95f, 0), new Vector3(0.7f, 0.78f, 0.42f), Material("base-shirt", new Color32(55, 126, 190, 255)));
            Primitive("Head", PrimitiveType.Sphere, root.transform, new Vector3(0, 1.85f, -0.03f), new Vector3(0.5f, 0.58f, 0.5f), skin);
            Primitive("Hair", PrimitiveType.Sphere, root.transform, new Vector3(0, 2.12f, -0.08f), new Vector3(0.54f, 0.26f, 0.48f), hair);
            Primitive("Left Arm", PrimitiveType.Capsule, root.transform, new Vector3(-0.55f, 0.92f, 0), new Vector3(0.17f, 0.62f, 0.17f), skin, new Vector3(0, 0, -15));
            Primitive("Right Arm", PrimitiveType.Capsule, root.transform, new Vector3(0.55f, 0.92f, 0), new Vector3(0.17f, 0.62f, 0.17f), skin, new Vector3(0, 0, 15));
            Primitive("Left Leg", PrimitiveType.Capsule, root.transform, new Vector3(-0.22f, 0.18f, 0), new Vector3(0.18f, 0.48f, 0.18f), dark);
            Primitive("Right Leg", PrimitiveType.Capsule, root.transform, new Vector3(0.22f, 0.18f, 0), new Vector3(0.18f, 0.48f, 0.18f), dark);
            Primitive("Left Shoe", PrimitiveType.Cube, root.transform, new Vector3(-0.22f, -0.18f, -0.08f), new Vector3(0.28f, 0.12f, 0.42f), Material("shoe-red", new Color32(224, 79, 95, 255)));
            Primitive("Right Shoe", PrimitiveType.Cube, root.transform, new Vector3(0.22f, -0.18f, -0.08f), new Vector3(0.28f, 0.12f, 0.42f), Material("shoe-red", new Color32(224, 79, 95, 255)));
            AddAttachmentSet(root, new Vector3(0, 1.78f, -0.47f), new Vector3(0, 2.24f, -0.05f), new Vector3(0, 2.18f, -0.04f), new Vector3(0, 1.15f, 0.34f), new Vector3(0, 0.35f, 0.45f));
            return root;
        }

        private static GameObject CreateDragonAvatar(Material green, Material gold, Material dark)
        {
            GameObject root = AvatarRoot("dragon");
            Primitive("Body", PrimitiveType.Sphere, root.transform, new Vector3(0, 0.82f, 0), new Vector3(0.98f, 0.86f, 0.72f), green);
            Primitive("Belly", PrimitiveType.Capsule, root.transform, new Vector3(0, 0.83f, -0.43f), new Vector3(0.42f, 0.62f, 0.11f), gold);
            Primitive("Neck", PrimitiveType.Capsule, root.transform, new Vector3(-0.12f, 1.36f, -0.18f), new Vector3(0.32f, 0.55f, 0.32f), green, new Vector3(0, 0, 8));
            Primitive("Head", PrimitiveType.Sphere, root.transform, new Vector3(-0.42f, 1.85f, -0.38f), new Vector3(0.62f, 0.42f, 0.5f), green);
            Primitive("Snout", PrimitiveType.Capsule, root.transform, new Vector3(-0.78f, 1.75f, -0.54f), new Vector3(0.32f, 0.24f, 0.48f), green, new Vector3(90, 0, 84));
            Primitive("Left Wing", PrimitiveType.Cube, root.transform, new Vector3(-0.92f, 1.02f, 0.22f), new Vector3(0.9f, 0.08f, 0.78f), Material("wing-orange", new Color32(220, 136, 34, 255)), new Vector3(0, 0, 26));
            Primitive("Right Wing", PrimitiveType.Cube, root.transform, new Vector3(0.92f, 1.02f, 0.22f), new Vector3(0.9f, 0.08f, 0.78f), Material("wing-orange", new Color32(220, 136, 34, 255)), new Vector3(0, 0, -26));
            Primitive("Tail", PrimitiveType.Capsule, root.transform, new Vector3(0.8f, 0.34f, 0.42f), new Vector3(0.18f, 0.78f, 0.18f), green, new Vector3(0, 0, -64));
            Primitive("Left Horn", PrimitiveType.Cylinder, root.transform, new Vector3(-0.55f, 2.24f, -0.36f), new Vector3(0.12f, 0.42f, 0.12f), gold, new Vector3(20, 0, -20));
            Primitive("Right Horn", PrimitiveType.Cylinder, root.transform, new Vector3(-0.18f, 2.27f, -0.34f), new Vector3(0.12f, 0.42f, 0.12f), gold, new Vector3(20, 0, 20));
            Primitive("Left Foot", PrimitiveType.Sphere, root.transform, new Vector3(-0.36f, -0.09f, -0.2f), new Vector3(0.3f, 0.17f, 0.36f), dark);
            Primitive("Right Foot", PrimitiveType.Sphere, root.transform, new Vector3(0.38f, -0.08f, -0.2f), new Vector3(0.3f, 0.17f, 0.36f), dark);
            AddAttachmentSet(root, new Vector3(-0.58f, 1.7f, -0.75f), new Vector3(-0.36f, 2.32f, -0.36f), new Vector3(-0.38f, 2.28f, -0.35f), new Vector3(0, 1.03f, 0.36f), new Vector3(0.72f, 0.34f, 0.48f));
            return root;
        }

        private static GameObject CreateBearAvatar(Material fur, Material skinLight, Material dark)
        {
            GameObject root = AvatarRoot("bear");
            Primitive("Body", PrimitiveType.Sphere, root.transform, new Vector3(0, 0.86f, 0), new Vector3(0.9f, 0.95f, 0.64f), fur);
            Primitive("Head", PrimitiveType.Sphere, root.transform, new Vector3(0, 1.82f, -0.04f), new Vector3(0.68f, 0.62f, 0.58f), fur);
            Primitive("Muzzle", PrimitiveType.Sphere, root.transform, new Vector3(0, 1.65f, -0.47f), new Vector3(0.34f, 0.22f, 0.2f), skinLight);
            Primitive("Left Ear", PrimitiveType.Sphere, root.transform, new Vector3(-0.43f, 2.25f, 0), new Vector3(0.24f, 0.24f, 0.18f), fur);
            Primitive("Right Ear", PrimitiveType.Sphere, root.transform, new Vector3(0.43f, 2.25f, 0), new Vector3(0.24f, 0.24f, 0.18f), fur);
            Primitive("Left Arm", PrimitiveType.Capsule, root.transform, new Vector3(-0.67f, 0.74f, 0), new Vector3(0.22f, 0.66f, 0.22f), fur, new Vector3(0, 0, -8));
            Primitive("Right Arm", PrimitiveType.Capsule, root.transform, new Vector3(0.67f, 0.74f, 0), new Vector3(0.22f, 0.66f, 0.22f), fur, new Vector3(0, 0, 8));
            Primitive("Left Foot", PrimitiveType.Cube, root.transform, new Vector3(-0.3f, -0.13f, -0.08f), new Vector3(0.38f, 0.16f, 0.42f), dark);
            Primitive("Right Foot", PrimitiveType.Cube, root.transform, new Vector3(0.3f, -0.13f, -0.08f), new Vector3(0.38f, 0.16f, 0.42f), dark);
            AddAttachmentSet(root, new Vector3(0, 1.64f, -0.62f), new Vector3(0, 2.28f, -0.04f), new Vector3(0, 2.24f, -0.04f), new Vector3(0, 1.05f, 0.36f), new Vector3(0, 0.28f, 0.44f));
            return root;
        }

        private static GameObject CreateElephantAvatar(Material elephant, Material gold, Material dark)
        {
            GameObject root = AvatarRoot("elephant");
            Primitive("Body", PrimitiveType.Capsule, root.transform, new Vector3(0, 0.86f, 0), new Vector3(0.9f, 0.9f, 0.62f), elephant);
            Primitive("Head", PrimitiveType.Sphere, root.transform, new Vector3(0, 1.78f, -0.05f), new Vector3(0.66f, 0.6f, 0.58f), elephant);
            Primitive("Trunk", PrimitiveType.Capsule, root.transform, new Vector3(0, 1.26f, -0.48f), new Vector3(0.16f, 0.58f, 0.16f), elephant, new Vector3(8, 0, 0));
            Primitive("Left Ear", PrimitiveType.Sphere, root.transform, new Vector3(-0.62f, 1.82f, 0), new Vector3(0.32f, 0.46f, 0.08f), elephant);
            Primitive("Right Ear", PrimitiveType.Sphere, root.transform, new Vector3(0.62f, 1.82f, 0), new Vector3(0.32f, 0.46f, 0.08f), elephant);
            Primitive("Left Tusk", PrimitiveType.Capsule, root.transform, new Vector3(-0.24f, 1.45f, -0.55f), new Vector3(0.08f, 0.3f, 0.08f), Material("ivory", new Color32(250, 241, 210, 255)), new Vector3(35, 0, -18));
            Primitive("Right Tusk", PrimitiveType.Capsule, root.transform, new Vector3(0.24f, 1.45f, -0.55f), new Vector3(0.08f, 0.3f, 0.08f), Material("ivory", new Color32(250, 241, 210, 255)), new Vector3(35, 0, 18));
            Primitive("Left Foot", PrimitiveType.Cube, root.transform, new Vector3(-0.28f, -0.12f, -0.08f), new Vector3(0.38f, 0.16f, 0.42f), dark);
            Primitive("Right Foot", PrimitiveType.Cube, root.transform, new Vector3(0.28f, -0.12f, -0.08f), new Vector3(0.38f, 0.16f, 0.42f), dark);
            Primitive("Head Jewel", PrimitiveType.Sphere, root.transform, new Vector3(0, 2.28f, -0.22f), new Vector3(0.16f, 0.16f, 0.08f), gold);
            AddAttachmentSet(root, new Vector3(0, 1.42f, -0.65f), new Vector3(0, 2.34f, -0.1f), new Vector3(0, 2.29f, -0.1f), new Vector3(0, 1.02f, 0.35f), new Vector3(0, 0.28f, 0.44f));
            return root;
        }

        private static GameObject CreateDevilAvatar(Material red, Material dark, Material gold)
        {
            GameObject root = CreateHumanAvatar(red, dark, dark);
            root.name = "devil";
            Primitive("Devil Left Wing", PrimitiveType.Cube, root.transform, new Vector3(-0.85f, 1.15f, 0.25f), new Vector3(0.72f, 0.08f, 0.7f), red, new Vector3(0, 0, 24));
            Primitive("Devil Right Wing", PrimitiveType.Cube, root.transform, new Vector3(0.85f, 1.15f, 0.25f), new Vector3(0.72f, 0.08f, 0.7f), red, new Vector3(0, 0, -24));
            Primitive("Tail", PrimitiveType.Capsule, root.transform, new Vector3(0.72f, 0.48f, 0.32f), new Vector3(0.12f, 0.62f, 0.12f), red, new Vector3(0, 0, -55));
            Primitive("Left Horn", PrimitiveType.Cylinder, root.transform, new Vector3(-0.22f, 2.45f, -0.08f), new Vector3(0.09f, 0.36f, 0.09f), gold, new Vector3(20, 0, -18));
            Primitive("Right Horn", PrimitiveType.Cylinder, root.transform, new Vector3(0.22f, 2.45f, -0.08f), new Vector3(0.09f, 0.36f, 0.09f), gold, new Vector3(20, 0, 18));
            return root;
        }

        private static GameObject CreateAngelAvatar(Material skin, Material white, Material gold)
        {
            GameObject root = CreateHumanAvatar(skin, Material("angel-hair", new Color32(238, 193, 93, 255)), white);
            root.name = "angel";
            Primitive("Robe", PrimitiveType.Capsule, root.transform, new Vector3(0, 0.7f, -0.01f), new Vector3(0.78f, 0.95f, 0.43f), white);
            Primitive("Left Wing", PrimitiveType.Cube, root.transform, new Vector3(-0.9f, 1.25f, 0.28f), new Vector3(0.76f, 0.08f, 0.84f), white, new Vector3(0, 0, 24));
            Primitive("Right Wing", PrimitiveType.Cube, root.transform, new Vector3(0.9f, 1.25f, 0.28f), new Vector3(0.76f, 0.08f, 0.84f), white, new Vector3(0, 0, -24));
            Primitive("Halo", PrimitiveType.Cylinder, root.transform, new Vector3(0, 2.55f, -0.02f), new Vector3(0.52f, 0.025f, 0.52f), gold, new Vector3(90, 0, 0));
            return root;
        }

        private static void CreateShirtPrefabs(bool overwrite)
        {
            foreach (string id in CharacterAvatarOptions.Tops)
            {
                GameObject root = PartRoot(id);
                Material mat = Material("part-shirt-" + id, new Color32(102, 217, 239, 255));
                Primitive("Chest", PrimitiveType.Cube, root.transform, Vector3.zero, id == CharacterAvatarOptions.Dress ? new Vector3(1.05f, 1.12f, 0.24f) : new Vector3(0.92f, 0.66f, 0.24f), mat);

                if (id != CharacterAvatarOptions.Vest && id != CharacterAvatarOptions.Armor)
                {
                    Primitive("Left Sleeve", PrimitiveType.Capsule, root.transform, new Vector3(-0.52f, -0.04f, 0), new Vector3(0.16f, 0.46f, 0.16f), mat, new Vector3(0, 0, -14));
                    Primitive("Right Sleeve", PrimitiveType.Capsule, root.transform, new Vector3(0.52f, -0.04f, 0), new Vector3(0.16f, 0.46f, 0.16f), mat, new Vector3(0, 0, 14));
                }

                if (id == CharacterAvatarOptions.Hoodie || id == CharacterAvatarOptions.Sweatshirt)
                {
                    Primitive("Pocket", PrimitiveType.Cube, root.transform, new Vector3(0, -0.23f, -0.14f), new Vector3(0.52f, 0.16f, 0.05f), Material("part-shirt-shadow", new Color32(43, 92, 114, 255)));
                }

                if (id == CharacterAvatarOptions.Armor)
                {
                    Primitive("Plate", PrimitiveType.Sphere, root.transform, new Vector3(0, 0.02f, -0.14f), new Vector3(0.52f, 0.52f, 0.08f), Material("armor-metal", new Color32(188, 198, 211, 255)));
                }

                SavePrefab(root, PartPrefabPath("Shirts", id), overwrite);
            }
        }

        private static void CreatePantsPrefabs(bool overwrite)
        {
            foreach (string id in CharacterAvatarOptions.Bottoms)
            {
                GameObject root = PartRoot(id);
                Material mat = Material("part-pants-" + id, new Color32(65, 105, 168, 255));
                Primitive("Waist", PrimitiveType.Cube, root.transform, new Vector3(0, 0.16f, 0), new Vector3(0.82f, 0.18f, 0.24f), mat);

                if (id == CharacterAvatarOptions.Skirt)
                {
                    Primitive("Skirt", PrimitiveType.Cube, root.transform, new Vector3(0, -0.1f, 0), new Vector3(0.96f, 0.45f, 0.24f), mat);
                }
                else
                {
                    Primitive("Left Leg", PrimitiveType.Capsule, root.transform, new Vector3(-0.22f, -0.33f, 0), new Vector3(0.18f, id == CharacterAvatarOptions.Shorts ? 0.34f : 0.72f, 0.18f), mat);
                    Primitive("Right Leg", PrimitiveType.Capsule, root.transform, new Vector3(0.22f, -0.33f, 0), new Vector3(0.18f, id == CharacterAvatarOptions.Shorts ? 0.34f : 0.72f, 0.18f), mat);
                }

                if (id == CharacterAvatarOptions.Cargo)
                {
                    Primitive("Left Pocket", PrimitiveType.Cube, root.transform, new Vector3(-0.37f, -0.28f, -0.13f), new Vector3(0.18f, 0.2f, 0.04f), Material("cargo-pocket", new Color32(35, 76, 107, 255)));
                    Primitive("Right Pocket", PrimitiveType.Cube, root.transform, new Vector3(0.37f, -0.28f, -0.13f), new Vector3(0.18f, 0.2f, 0.04f), Material("cargo-pocket", new Color32(35, 76, 107, 255)));
                }

                SavePrefab(root, PartPrefabPath("Pants", id), overwrite);
            }
        }

        private static void CreateShoePrefabs(bool overwrite)
        {
            foreach (string id in CharacterAvatarOptions.Shoes)
            {
                if (id == CharacterAvatarOptions.NoShoes)
                {
                    continue;
                }

                GameObject root = PartRoot(id);
                Material mat = Material("part-shoe-" + id, new Color32(224, 79, 95, 255));
                Primitive("Shoe", PrimitiveType.Cube, root.transform, Vector3.zero, id == CharacterAvatarOptions.Boots ? new Vector3(0.34f, 0.34f, 0.5f) : new Vector3(0.34f, 0.16f, 0.5f), mat);
                Primitive("Toe Highlight", PrimitiveType.Cube, root.transform, new Vector3(0, 0.05f, -0.18f), new Vector3(0.24f, 0.04f, 0.12f), Material("shoe-highlight", new Color32(255, 178, 190, 255)));
                SavePrefab(root, PartPrefabPath("Shoes", id), overwrite);
            }
        }

        private static void CreateAccessoryPrefabs(bool overwrite)
        {
            SavePrefab(CreateMask(), PartPrefabPath("Accessories", CharacterAvatarOptions.Mask), overwrite);
            SavePrefab(CreateGlasses(), PartPrefabPath("Accessories", CharacterAvatarOptions.Glasses), overwrite);
            SavePrefab(CreateCap(), PartPrefabPath("Accessories", CharacterAvatarOptions.Cap), overwrite);
            SavePrefab(CreateCrown(), PartPrefabPath("Accessories", CharacterAvatarOptions.Crown), overwrite);
            SavePrefab(CreateHeadphones(), PartPrefabPath("Accessories", CharacterAvatarOptions.Headphones), overwrite);
            SavePrefab(CreateWings(), PartPrefabPath("Accessories", CharacterAvatarOptions.Wings), overwrite);
            SavePrefab(CreateHalo(), PartPrefabPath("Accessories", CharacterAvatarOptions.Halo), overwrite);
            SavePrefab(CreateHorns(), PartPrefabPath("Accessories", CharacterAvatarOptions.Horns), overwrite);
            SavePrefab(CreateTail(), PartPrefabPath("Accessories", CharacterAvatarOptions.Tail), overwrite);
        }

        private static GameObject CreateMask()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Mask);
            Primitive("Mask", PrimitiveType.Cube, root.transform, Vector3.zero, new Vector3(0.62f, 0.2f, 0.05f), Material("mask-white", new Color32(232, 247, 255, 255)));
            Primitive("Left Strap", PrimitiveType.Cube, root.transform, new Vector3(-0.42f, 0, 0.01f), new Vector3(0.22f, 0.035f, 0.035f), Material("mask-strap", new Color32(210, 232, 240, 255)));
            Primitive("Right Strap", PrimitiveType.Cube, root.transform, new Vector3(0.42f, 0, 0.01f), new Vector3(0.22f, 0.035f, 0.035f), Material("mask-strap", new Color32(210, 232, 240, 255)));
            return root;
        }

        private static GameObject CreateGlasses()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Glasses);
            Material mat = Material("glasses-black", new Color32(12, 18, 26, 255));
            Primitive("Bridge", PrimitiveType.Cube, root.transform, Vector3.zero, new Vector3(0.62f, 0.035f, 0.035f), mat);
            Primitive("Left Lens", PrimitiveType.Cube, root.transform, new Vector3(-0.22f, 0, -0.01f), new Vector3(0.2f, 0.16f, 0.035f), mat);
            Primitive("Right Lens", PrimitiveType.Cube, root.transform, new Vector3(0.22f, 0, -0.01f), new Vector3(0.2f, 0.16f, 0.035f), mat);
            return root;
        }

        private static GameObject CreateCap()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Cap);
            Material mat = Material("cap-blue", new Color32(36, 79, 158, 255));
            Primitive("Cap Dome", PrimitiveType.Sphere, root.transform, new Vector3(0, 0, 0), new Vector3(0.56f, 0.22f, 0.5f), mat);
            Primitive("Brim", PrimitiveType.Cube, root.transform, new Vector3(0, -0.09f, -0.35f), new Vector3(0.54f, 0.055f, 0.26f), mat);
            return root;
        }

        private static GameObject CreateCrown()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Crown);
            Material mat = Material("crown-gold", new Color32(255, 211, 106, 255));
            Primitive("Base", PrimitiveType.Cube, root.transform, new Vector3(0, -0.08f, 0), new Vector3(0.58f, 0.09f, 0.16f), mat);
            Primitive("Center Point", PrimitiveType.Cube, root.transform, new Vector3(0, 0.08f, 0), new Vector3(0.16f, 0.28f, 0.16f), mat, new Vector3(0, 0, 45));
            Primitive("Left Point", PrimitiveType.Cube, root.transform, new Vector3(-0.22f, 0.04f, 0), new Vector3(0.13f, 0.2f, 0.13f), mat, new Vector3(0, 0, 45));
            Primitive("Right Point", PrimitiveType.Cube, root.transform, new Vector3(0.22f, 0.04f, 0), new Vector3(0.13f, 0.2f, 0.13f), mat, new Vector3(0, 0, 45));
            return root;
        }

        private static GameObject CreateHeadphones()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Headphones);
            Material dark = Material("headphones-dark", new Color32(10, 17, 26, 255));
            Primitive("Band", PrimitiveType.Cube, root.transform, new Vector3(0, 0.2f, 0), new Vector3(0.9f, 0.055f, 0.055f), dark);
            Primitive("Left Cup", PrimitiveType.Cube, root.transform, new Vector3(-0.5f, -0.04f, 0), new Vector3(0.18f, 0.32f, 0.16f), dark);
            Primitive("Right Cup", PrimitiveType.Cube, root.transform, new Vector3(0.5f, -0.04f, 0), new Vector3(0.18f, 0.32f, 0.16f), dark);
            return root;
        }

        private static GameObject CreateWings()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Wings);
            Material white = Material("wings-white", new Color32(248, 250, 252, 255));
            Primitive("Left Wing", PrimitiveType.Cube, root.transform, new Vector3(-0.62f, 0, 0), new Vector3(0.88f, 0.08f, 0.72f), white, new Vector3(0, 0, 25));
            Primitive("Right Wing", PrimitiveType.Cube, root.transform, new Vector3(0.62f, 0, 0), new Vector3(0.88f, 0.08f, 0.72f), white, new Vector3(0, 0, -25));
            return root;
        }

        private static GameObject CreateHalo()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Halo);
            Primitive("Halo", PrimitiveType.Cylinder, root.transform, Vector3.zero, new Vector3(0.62f, 0.035f, 0.62f), Material("halo-gold", new Color32(255, 211, 106, 255)), new Vector3(90, 0, 0));
            return root;
        }

        private static GameObject CreateHorns()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Horns);
            Material mat = Material("horn-red", new Color32(178, 55, 55, 255));
            Primitive("Left Horn", PrimitiveType.Cylinder, root.transform, new Vector3(-0.22f, 0, 0), new Vector3(0.08f, 0.36f, 0.08f), mat, new Vector3(20, 0, -18));
            Primitive("Right Horn", PrimitiveType.Cylinder, root.transform, new Vector3(0.22f, 0, 0), new Vector3(0.08f, 0.36f, 0.08f), mat, new Vector3(20, 0, 18));
            return root;
        }

        private static GameObject CreateTail()
        {
            GameObject root = PartRoot(CharacterAvatarOptions.Tail);
            Primitive("Tail", PrimitiveType.Capsule, root.transform, Vector3.zero, new Vector3(0.12f, 0.78f, 0.12f), Material("tail-red", new Color32(178, 55, 55, 255)), new Vector3(0, 0, -55));
            return root;
        }

        private static void AddAttachmentSet(GameObject root, Vector3 face, Vector3 hat, Vector3 horns, Vector3 shirt, Vector3 pants)
        {
            AvatarAttachmentSet set = root.AddComponent<AvatarAttachmentSet>();
            set.facePoint = Point("FacePoint", root.transform, face);
            set.hatPoint = Point("HatPoint", root.transform, hat);
            set.hornsPoint = Point("HornsPoint", root.transform, horns);
            set.wingsPoint = Point("WingsPoint", root.transform, new Vector3(0, 1.1f, 0.42f));
            set.tailPoint = Point("TailPoint", root.transform, new Vector3(0.65f, 0.35f, 0.42f));
            set.shirtPoint = Point("ShirtPoint", root.transform, shirt);
            set.pantsPoint = Point("PantsPoint", root.transform, pants);
            set.leftShoePoint = Point("LeftShoePoint", root.transform, new Vector3(-0.26f, -0.2f, -0.12f));
            set.rightShoePoint = Point("RightShoePoint", root.transform, new Vector3(0.26f, -0.2f, -0.12f));
        }

        private static Transform Point(string name, Transform parent, Vector3 position)
        {
            Transform point = new GameObject(name).transform;
            point.SetParent(parent, false);
            point.localPosition = position;
            return point;
        }

        private static GameObject AvatarRoot(string name)
        {
            GameObject root = new GameObject(name);
            root.transform.localScale = Vector3.one;
            return root;
        }

        private static GameObject PartRoot(string name)
        {
            return new GameObject(name);
        }

        private static GameObject Primitive(string name, PrimitiveType type, Transform parent, Vector3 position, Vector3 scale, Material material, Vector3? rotation = null)
        {
            GameObject primitive = GameObject.CreatePrimitive(type);
            primitive.name = name;
            primitive.transform.SetParent(parent, false);
            primitive.transform.localPosition = position;
            primitive.transform.localRotation = Quaternion.Euler(rotation ?? Vector3.zero);
            primitive.transform.localScale = scale;

            Renderer renderer = primitive.GetComponent<Renderer>();
            if (renderer != null)
            {
                renderer.sharedMaterial = material;
            }

            Collider collider = primitive.GetComponent<Collider>();
            if (collider != null)
            {
                Object.DestroyImmediate(collider);
            }

            return primitive;
        }

        private static void SavePrefab(GameObject root, string path, bool overwrite)
        {
            if (!overwrite && File.Exists(path))
            {
                Object.DestroyImmediate(root);
                return;
            }

            Directory.CreateDirectory(Path.GetDirectoryName(path));
            PrefabUtility.SaveAsPrefabAsset(root, path);
            Object.DestroyImmediate(root);
        }

        private static AvatarPartPrefab[] BuildCatalog(string category, AvatarAttachmentSlot slot, string[] ids)
        {
            AvatarPartPrefab[] result = new AvatarPartPrefab[ids.Length];

            for (int index = 0; index < ids.Length; index++)
            {
                result[index] = new AvatarPartPrefab
                {
                    id = ids[index],
                    slot = slot,
                    prefab = LoadPart(category, ids[index])
                };
            }

            return result;
        }

        private static AvatarPartPrefab[] BuildAccessoryCatalog()
        {
            return new[]
            {
                Part(CharacterAvatarOptions.Glasses, AvatarAttachmentSlot.Face, "Accessories"),
                Part(CharacterAvatarOptions.Cap, AvatarAttachmentSlot.Hat, "Accessories"),
                Part(CharacterAvatarOptions.Crown, AvatarAttachmentSlot.Hat, "Accessories"),
                Part(CharacterAvatarOptions.Mask, AvatarAttachmentSlot.Face, "Accessories"),
                Part(CharacterAvatarOptions.Headphones, AvatarAttachmentSlot.Face, "Accessories"),
                Part(CharacterAvatarOptions.Wings, AvatarAttachmentSlot.Wings, "Accessories"),
                Part(CharacterAvatarOptions.Halo, AvatarAttachmentSlot.Hat, "Accessories"),
                Part(CharacterAvatarOptions.Horns, AvatarAttachmentSlot.Horns, "Accessories"),
                Part(CharacterAvatarOptions.Tail, AvatarAttachmentSlot.Tail, "Accessories")
            };
        }

        private static AvatarPartPrefab[] BuildShoeCatalog()
        {
            string[] ids =
            {
                CharacterAvatarOptions.Sneakers,
                CharacterAvatarOptions.Boots,
                CharacterAvatarOptions.Sandals,
                CharacterAvatarOptions.Slippers
            };
            AvatarPartPrefab[] result = new AvatarPartPrefab[ids.Length * 2];

            for (int index = 0; index < ids.Length; index++)
            {
                GameObject prefab = LoadPart("Shoes", ids[index]);
                result[index * 2] = new AvatarPartPrefab { id = ids[index], slot = AvatarAttachmentSlot.LeftShoe, prefab = prefab };
                result[index * 2 + 1] = new AvatarPartPrefab { id = ids[index], slot = AvatarAttachmentSlot.RightShoe, prefab = prefab };
            }

            return result;
        }

        private static AvatarPartPrefab Part(string id, AvatarAttachmentSlot slot, string category)
        {
            return new AvatarPartPrefab
            {
                id = id,
                slot = slot,
                prefab = LoadPart(category, id)
            };
        }

        private static GameObject LoadAvatar(string id)
        {
            return AssetDatabase.LoadAssetAtPath<GameObject>(AvatarPrefabPath(id));
        }

        private static GameObject LoadPart(string category, string id)
        {
            return AssetDatabase.LoadAssetAtPath<GameObject>(PartPrefabPath(category, id));
        }

        private static string AvatarPrefabPath(string id)
        {
            return AvatarPathRoot + "/" + id + ".prefab";
        }

        private static string PartPrefabPath(string category, string id)
        {
            return PartPathRoot + "/" + category + "/" + id + ".prefab";
        }

        private static Material Material(string name, Color color)
        {
            string path = MaterialPathRoot + "/" + name + ".mat";
            Material material = AssetDatabase.LoadAssetAtPath<Material>(path);

            if (material != null)
            {
                material.color = color;
                return material;
            }

            Shader shader = Shader.Find("Standard");
            if (shader == null)
            {
                shader = Shader.Find("Universal Render Pipeline/Lit");
            }

            material = new Material(shader)
            {
                name = name,
                color = color
            };
            AssetDatabase.CreateAsset(material, path);
            return material;
        }

        private static void EnsureFolders()
        {
            EnsureFolder("Assets", "Resources");
            EnsureFolder("Assets/Resources", "GeneratedAvatarBuilder");
            EnsureFolder(RootPath, "Avatars");
            EnsureFolder(RootPath, "Parts");
            EnsureFolder(RootPath, "Materials");
            EnsureFolder(PartPathRoot, "Accessories");
            EnsureFolder(PartPathRoot, "Pants");
            EnsureFolder(PartPathRoot, "Shirts");
            EnsureFolder(PartPathRoot, "Shoes");
        }

        private static void EnsureFolder(string parent, string child)
        {
            string path = parent + "/" + child;

            if (!AssetDatabase.IsValidFolder(path))
            {
                AssetDatabase.CreateFolder(parent, child);
            }
        }
    }
}
