using System;
using UnityEngine;

namespace SaferTogether.UnityClient
{
    // the only selectable avatars are the Quaternius pack characters. ids are stored as
    // "pack:<character>" (matches Services/avatarService.js) and each maps 1:1 to a prefab and
    // a thumbnail sprite under Resources/SaferTogetherAvatars, generated by the editor installer.
    public static class AvatarCatalog
    {
        public const string ResourcesRoot = "SaferTogetherAvatars";
        public const string ThumbnailFolder = ResourcesRoot + "/Thumbs";
        public const string IdPrefix = "pack:";
        public const string WalkingParam = "Walking";
        public const string DefaultCharacter = "adventurer";

        // character ids (lower-case, must match avatarService.js PACK_CHARACTERS + the prefab names)
        public static readonly string[] Characters =
        {
            "adventurer",
            "beach",
            "casual",
            "casual2",
            "farmer",
            "king",
            "punk",
            "spacesuit",
            "suit",
            "swat",
            "worker"
        };

        // short Hebrew labels shown under each thumbnail (order matches Characters)
        public static readonly string[] DisplayNames =
        {
            "הרפתקן",      // adventurer
            "חוף",          // beach
            "יומיומי",      // casual
            "רגיל",        // casual2
            "חקלאי",        // farmer
            "מלך",          // king
            "פאנק",         // punk
            "אסטרונאוט",    // spacesuit
            "חליפה",        // suit
            "שוטר",        // swat
            "פועל"          // worker
        };

        // accept "pack:swat" or a bare "swat" (any case) and return a valid character id
        public static string ResolveCharacter(string avatarOrCharacterId)
        {
            string value = string.IsNullOrEmpty(avatarOrCharacterId)
                ? ""
                : avatarOrCharacterId.Trim().ToLowerInvariant();

            if (value.StartsWith(IdPrefix, StringComparison.Ordinal))
            {
                value = value.Substring(IdPrefix.Length);
            }

            return Array.IndexOf(Characters, value) >= 0 ? value : DefaultCharacter;
        }

        // wrap a character id into the stored avatar id ("pack:<character>")
        public static string ToAvatarId(string character)
        {
            return IdPrefix + ResolveCharacter(character);
        }

        // friendly label for a character id
        public static string DisplayNameFor(string character)
        {
            int index = Array.IndexOf(Characters, ResolveCharacter(character));
            return index >= 0 ? DisplayNames[index] : ResolveCharacter(character);
        }

        // load the runtime prefab for a character (null if the installer hasn't run yet)
        public static GameObject LoadPrefab(string character)
        {
            return Resources.Load<GameObject>(ResourcesRoot + "/" + ResolveCharacter(character));
        }

        // load the square thumbnail sprite for a character (null when missing)
        public static Sprite LoadThumbnail(string character)
        {
            return Resources.Load<Sprite>(ThumbnailFolder + "/" + ResolveCharacter(character));
        }
    }
}
